imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false
        
liip_functional_test: 
    cache_sqlite_db: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db

web_profiler:
    toolbar: false
    intercept_redirects: false

# Swiftmailer Configuration
swiftmailer:
    delivery_address: %mailer_delivery_address%
    disable_delivery: false 