imports:
    - { resource: config.yml }
    - { resource: app/config_dev.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
        name: DEVSID

web_profiler:
    toolbar: true 
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

assetic:
    use_controller: true


# Swiftmailer Configuration
swiftmailer:
    delivery_address: %mailer_delivery_address%
    disable_delivery: false 

#jns_xhprof:
#    location_lib:     /opt/local/www/php55-xhprof/xhprof_lib/utils/xhprof_lib.php
#    location_runs:    /opt/local/www/php55-xhprof/xhprof_lib/utils/xhprof_runs.php
    # location_config: /opt/local/lib/php55/include_path/xhprof_lib/config.php
#    location_web:    http://localhost:8988
#    enabled:         true
    
#swiftmailer:
#    delivery_address: me@example.com
