
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
        
    acl:
        connection: default
        
    role_hierarchy:
        ROLE_MEMBER: ROLE_USER
        ROLE_ADMIN: ROLE_MEMBER
        ROLE_ADMIN_EDITOR: ROLE_ADMIN
        ROLE_ADMIN_MANAGER: ROLE_ADMIN
        ROLE_ADMIN_PARTNER: ROLE_ADMIN
        ROLE_ADMIN_BOSS: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ ROLE_USER , ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(admin/login|admin/locale)$
            security: false
        
        secured_area:
            pattern:    ^/admin/
            form_login:
                # always_use_default_target_path: true
                default_target_path: app_admin_dashboard
                check_path: app_admin_check
                login_path: app_admin_login
                username_parameter: login[username]
                password_parameter: login[password]
                csrf_parameter: login[_token]
                
                # csrf_parameter: form[_token1]
                # intention:      authenticate
                # csrf_provider: form.csrf_provider
                
                # by default, the login form *must* be a POST, not a GET
                post_only:      true
                remember_me:    false

            logout:
                path:   app_admin_logout
                target: app_admin_dashboard

        main:
            pattern: ^/
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                # success_handler: ccdn_user_security.component.authentication.handler.login_success_handler
                username_parameter: login[username]
                password_parameter: login[password]
                csrf_parameter: login[_token]
                failure_path:   null
                post_only:      true
                remember_me:    true
                #failure_handler: app.user.ajax_handler
                #success_handler: app.user.ajax_handler

            logout:
                path:   /logout
                target: /
                # success_handler: ccdn_user_security.component.authentication.handler.logout_success_handler
            anonymous:  true
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
