type:
    birthday: App\AdminBundle\Compiler\MetaType\Form\Birthday
    bool: App\AdminBundle\Compiler\MetaType\Form\Bool
    checkbox: App\AdminBundle\Compiler\MetaType\Form\Checkbox
    choice: App\AdminBundle\Compiler\MetaType\Form\Choice
    color: App\AdminBundle\Compiler\MetaType\Form\Color
    county: App\AdminBundle\Compiler\MetaType\Form\Country 
    datetime: App\AdminBundle\Compiler\MetaType\Form\Datetime
    date: App\AdminBundle\Compiler\MetaType\Form\Date
    time: App\AdminBundle\Compiler\MetaType\Form\Time
    email: App\AdminBundle\Compiler\MetaType\Form\Email
    embed: App\AdminBundle\Compiler\MetaType\Form\Embed
    entity: App\AdminBundle\Compiler\MetaType\Form\Entity
    file: App\AdminBundle\Compiler\MetaType\Form\File
    hidden: App\AdminBundle\Compiler\MetaType\Form\Hidden
    html: App\AdminBundle\Compiler\MetaType\Form\Html
    image: App\AdminBundle\Compiler\MetaType\Form\Image
    integer: App\AdminBundle\Compiler\MetaType\Form\Integer
    language: App\AdminBundle\Compiler\MetaType\Form\Language
    locale: App\AdminBundle\Compiler\MetaType\Form\Locale
    markdown: App\AdminBundle\Compiler\MetaType\Form\Markdown
    money: App\AdminBundle\Compiler\MetaType\Form\Money
    password: App\AdminBundle\Compiler\MetaType\Form\Password
    percent: App\AdminBundle\Compiler\MetaType\Form\Percent
    radio: App\AdminBundle\Compiler\MetaType\Form\Radio
    search: App\AdminBundle\Compiler\MetaType\Form\Search
    text: App\AdminBundle\Compiler\MetaType\Form\Text
    textarea: App\AdminBundle\Compiler\MetaType\Form\Textarea
    timezone: App\AdminBundle\Compiler\MetaType\Form\Timezone
    url: App\AdminBundle\Compiler\MetaType\Form\Url
    workflow: App\AdminBundle\Compiler\MetaType\Form\Workflow
    owner: App\AdminBundle\Compiler\MetaType\Form\Owner
    range: App\AdminBundle\Compiler\MetaType\Form\Range
    combobox: App\AdminBundle\Compiler\MetaType\Form\Combobox